name = "creatoon"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 5000

[[kv_namespaces]]
binding = "RATE_LIMITER"
id = "37f3d4ab8ea34c8fb80e9b16c6435690"